---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: xxu39114
spec:
  encryptedData:
    client_secret: AgBVYaxLomrPXgctHWyfGbmmE3zAUKjS3/neuM3xLkDz/RqluTx87tFer8W/ctk1Mowz+b260akRsmAHet8rJFWvNbpY5Zwk0jDOps6wwtslW8Pi6L0H3G3IY0HCnYlFwr0WhM7v31wW4ANWTtngjgfS8NhQ5U1/MiiE+Qs43zFAHn9fa+Z2S7m+ggdBtl5lDHUb3f4Rj4hyvSyd6QYo8+S9ul9iwUimw/IuaEQ85aVrhhX/zNdQ5cCCLXGIqF0wXqH4zQBOe0QZ6fBNFbnTq+B0oxyRWM9y/qezlvo6plR9af3dzDU0g0Mcw12NSZpWNhuD3ID/Z1nj+saBzqS1HSwxb1U+fv5O49kPYNS822bzUHm32jvM1DZlhsk2hk1XqlJTD7bFBw6xzNwMhaJ8/rdnvxkWWclP1yKaYwAn3o8mGTjjXikRjo1hZAZ1/XNarga6CPqZaC9/A01RiKmSB4shJ0ON2E81PCvR4CHbHJty/4jBnyIMciJwDRCbPPltSkPoXdMIBz+zkTtdY+JTeP2LLhDtcYLNqZU1wh0+0//P+75OPq7Cm8IMxc0a11Oajhv+ewD7bh7Yc38GNUl5eMMhVBjOxw8Iv2g5b+0J1HhYWcvYamAT4E4U2YrjP8Ev8QoFfdmApw5wQpLJfe2uehzvfRc3lpwsifl1vuLpFb/VUeitH70+Dt64ddTcLIvUzOjKOUKi0r0MoxY2Sza2zALaQ5gUu0g4254=
    cookie_secret: AgANsXeWLiKaDeZtTd/ViEJc5X3gwvDfXa3eBSnCL9aqmeOjwXFp3EAHlveVyBmffWpRZIacaI6JayNRNsCP4d/02/Mves8H+pkm0AqOEXEk6FD0WwLkQf4s3+JhEBIvNxagp8wCUpoym+suFuXNw8PxMQ8Q19SQ6/7+WW+08L8IxYGpS5HIbMKl681vi3fv6ncBT87OKdVheQDrtFZPwz2SSGuqNIMHiSn9WxZuk2PJSqEOJD3QN6S5eiKZJfJOSHXmY7jdSLXaNKmxeKRQFSDPxu04Wsfkr5jdzuNQVJG3RfETwasdW6ltLnn9zdgscSlfcH3a/B8cZAkhkK0kdzSp6RXVJV40q29qBO5IqndaOKQ3996tyJSR6e0qVr03ml2d0j1yVZY4luHvRh3xCSDUbwAUG3L+yZor4/yeqgHIJbc/cFU31CBMN3jrBVgP18L9L+oLG4zfRctvq3kePP/Pi6jBQF7qF+w8/3/zuRScpPmnEqG7SNdyU68YmSLGjlA7XosX1pGL4+VOVvGZpzhthwomfgiXbm39n25RZR5KAKz2VT8PISsoWREFQomP5aZoOil7sfkSYOZwN94TUCFQq4u8gYee68dMCW/bFjE0Ofs+zQO/2az8EvhCuFZFdrHye9u7EE0JZIoRW/gR28O+oGodlkXn994hBMJhixl7njji+mT3f+/WL7lvEK9tGJthxSELCb3dZpN81aS4zIoIrszl4QD4h4T42UOaGSzwFQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: xxu39114
