---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: xxu39114
spec:
  encryptedData:
    client_secret: AgCw6RxvK9umw4zcwfQeLcFL1hYZ+S+1vDvdnwCkDy0obqlYOGka6eGLNt4z5AHfUcbH7WpODlUShkkjdIcPBlvRn/eWCSSvX1OxxEk73epwrhnK9Wa0ortRElyRDjibbrprVeKrBY9S4kSOStlDPiCevOXTSngiALaBSm5ZR0gnFJkDjjssCPE7WWSzwAWwlh1YqX5Q5CH0jk/z5AsTr+GyVfgmWZm92c0nOlkd87cpQHNzXgpFlD7VgTB+eEkHBz5BGDT9V3Yj1pOEUBN1Cu4/uuEvzdJ4P0UH1DVR8oohRewJDvo/9Ovi5FvRb0LPl76SbT6wpXec/KLTfmaLlLf7Bup5FPmaGEqouFnTOY0TYuUN4N0iqupw3yCzDR9V/rR11EdiPgpjH1oO7RHcVV8l9oJTlwKSWTdjVPW2V5LSY2/UIVDdImloHTUirOyC3jU9It22vW8QMU4Mwo6B9Ee71K8hkqJskwjQIIviLaU9X1twgElArIA7H0noCUaR4ASY3MVkSkSr80YiPTuWGkqcPJlz6YQmRYRHTm0Uc54egEzC6tel6lAWYfB95CPCUm1DUTww7jHYgJyQf5KBQluDwP/ATUXyFrbGYzO+r4OFQkXZ3hrj/6KvAe22d6FKxeV6RINWPMSJMyG9ZjbB/ZweU2Xby++F9PzYJntbnzAZutOoqTpcUmib90qiO3rOE9WiVrIqpEWnSy9Atbimo743X0EP0wRwMK0=
    cookie_secret: AgChFEGtDBB3eGbQn7WuZQH56mVDEAYfbw7gO3gXViWj3HWadkZmt+4Uoi7vOgZ4ROpXbs3D8iYYCobaO49LAPoD91oOfVmCaT6XVb+LaiV0x3/hOdS0oORP8WTIlAY9fA4WqVOcDC+DKqW3BTaDkZJWthno2wZ/tGu2z5bA/k1XGwVQHNtrm9KK7rkQBR8BlQTWSHZAh5022nUgocxOJMl9o37vU85FzPF+CdYTEJOtsGwci3lF8lVvOWpykRY3d+OR0wKeHoqhokV2c9hPXnArIdL8FL2QRWPqLRnfpf0yrGk2a9lQ3wkWvVOiFUuNFhCmCcZGEnKRMHZ8FFwqF2Yf05cpIL6rVweshlX0B164u0BOpz4VlK9lNkBhv9gFLqnUrxNwndc9CjugpOiUzW6bVgcWnKeRWeRRT71Kg3BoGmIyYNAbU8CjIU9xJqHpNAx4Csy5T/gjxf+Ry8Lye6yOqsUY4DWR9Y72s6KGjUQMXAlD/EAAYj6X0s9ME915uUsX9z7Tx0dSA2OXmrtDJHGnUv0lvKUXtGUewCetfv12kscGc0YC+cnAfyTVX+VuSNE0Pn+L4KI+g2whq844JSWYBePJx2UbWOwfVTxjYbvB3CgAWUp6TmMVOAlxTAL8M/VT5eK50EYxaTdXL9iH/1BlKrzjTcPd7sK0K29FJxtRO+Vk5lr5GKAXZeqwPYDaXERJ1p15fhkJabMrNED0zEdEi5x4HLrUTlWh7d2KipOjHuhAP3+8OZYq4AqLag==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: xxu39114
