---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: xxu39114
spec:
  encryptedData:
    client_secret: AgAhGW6JjjUomACVGWtPRPpz45M4T790dlrOcuGg4UZ9w2Jihw3cofBoT3pvU4Yffc+xj6oXlfgkYY422hPCHhM019FaXsv42LUGMeCSvjORqS82dNhAaiilLI/043OGUG519bqklSxIk4sLxBj47zV7z5pQaMhkxNBSkInSm1fy9f8hF8VBrV6R3KtL+JbQ1wfx3m4edaJQnj6FnoMiCIyE6rXK77TFeSjstbWntpNyMIJ3ZRMoaDYJvZOe1Z+TI/Iu7CLatlA3X1hRtsGkbzBgkpGYh9+H+Lb3N43FiNGJZRg17aefEUIkoPOhT7KkV0T3ukk9cP97Dzd+2oaFBwAvLgwIfcCMS6uWywVNWyMBSYSItRb8bCsgtRJszbypWlg/aO/BfV1MZEowPg4fyBe2liUG8WVMj6rY/DYdH6WbzSkm4gQE5tb0ITSmvLENHIrljEOjsA3hi+VxsptyRGzZobeW4xV+l3hsr2WJLM9mCNR8Kp94M6jI2PuPay4WsorsHQ9cp6lrz5dyEoGZrKFlqClsy2FMLZFwM14qnwlTzxoz3unKcWbrjdJ0Muqu+IbPL3eh1Fg5/TmQ7jL8OBF0Ca2usUNDNPvt7ufES8WhVnzSLPi++yfUH9NXK8zF6bp/r7Y80RrG2OmVsvj7gG3YUKuADrkQgkESxWm5buNBiXQudBVcwQ6wxTojZnhD2h26LX03eHg5zNG0wIaIrYLsQbeJhIUx/Fk=
    cookie_secret: AgABmkZAI3DCZi3VhjViARjhxosi3Etz6HXtUi0gdFd2CPTjASTkjyTLa2MzsfXiOEPznwlZ8ZTZrUMYNrz9rOFcyWC0W6e0pXfFDSmjUkkLtn2tcHLyo4Rl3QPNoRskJ+6VD8+/Po1lVx3tMkCVMUxa7qNVBA5kedy+dFMHYOqSlGYFsdKn4BuMsYLAfF+1Uu/wx4KVU03RWh6OinPP/KYuFgQETyOOQbHrwUaYvA/Bu77B94SwnAhaizun0ra8Fmjg+AF4r9gobjjhh00FVuvfC7GMBsn4Bh5Kj0wTUmd3IGTygB94m9tSEaSMJMidbjCo8dntqIdvvvy40CnpMV+CzvtErh3u17koXx0IqkLz0z6NNj6LLM+s06fKhefB5ggiXVeW1daQyfjv+dOUvWFy/CV4J+jb5xrp/x2hA5GkoVnllrp2yCgE/ILai0Gc1+iddqkyVJNFGYFndwFsEHV7mdCtV4+yQ9rctz6YCLiJXkPznS/fyC+2xLnxL83sbeQub13TyWIooM8Z9JaZkiUT9K98VVIPA4MsD0LOdt+4/STcNQGhW9JTBScdxXWzsHawWzwSa2ewEOqi9EZ2YBv4LQq03hHHcBTEgiyhhX5/x6FE8bkwkkQBuz/4wTD6Pwo6msE6tY2c+rnagADfKs9AdqSKT1oQukNivZQ+dkkgs4g1jXoQhLU/2KKPD4mCH9g8azmG/4YNssP74IWJoDZQwpurllle1fJSsywqnkZGYg==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: xxu39114
